import "./globals.css";
import Link from "next/link";
import HeaderComponent from "@/app/navbar/page";
import FooterComponent from "@/app/footer/page";

export const metadata = {
  title: "DICO AJI PORTFOLIO",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen dark:bg-[#040704] dark:text-[#626262] ">
          <HeaderComponent />
          {children}
          <div className="mt-[100px]">
            <FooterComponent />
          </div>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>
        <script src="https://unpkg.com/embla-carousel/embla-carousel.umd.js"></script>
      </body>
    </html>
  );
}
